[package]
name = "rs-promql2json"
version = "0.1.0"
edition = "2024"

description = "Converts the PromQL to a json."
license = "Apache-2.0"
repository = "https://github.com/takanoriyanagitani/rs-promql2json"
homepage = "https://github.com/takanoriyanagitani/rs-promql2json"
documentation = "https://docs.rs/rs-promql2json/latest"
keywords = ["promql", "prometheus", "json"]

exclude = [
]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "forbid"
expect_used = "forbid"
panic = "forbid"

[profile.release-wasi]
inherits = "release"
lto = true
strip = true
opt-level = 's'
codegen-units = 1

[dependencies.serde_json]
version = "1"
default-features = false
features = [
  "std",
]

[dependencies.promql-parser]
version = "0.10"
default-features = false
features = [
  "ser",
]
